---
- name: Install Apache and Python3
  hosts: webservers
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install Apache
      apt:
        name: apache2
        state: present
      become: true

    - name: Install Python 3 and pip
      apt:
        name: python3
        state: present
      become: true

    - name: Install python3-pip package
      apt:
        name: python3-pip
        state: present
      become: true

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes
      become: true
